services:
  customer-core:
    build:
      context: ../customer-core
    volumes:
      - ./config/customer-core:/config

  customer-management:
    build:
      context: ../customer-management
    depends_on:
      - customer-core
    ports:
      - 8080:8080
    volumes:
      - ./config/customer-management:/config
      - ../customer-core:/app/packages/customer-core

  test:
    build:
      context: ./test
    depends_on:
      - customer-management
    volumes:
      - ../customer-core:/customer-core
