services:
  customer-core:
    build:
      context: ../customer-core
    volumes:
      - ./config/customer-core:/config

  customer-management:
    build:
      context: ..
      dockerfile: customer-management/Dockerfile
    depends_on:
      - customer-core
    ports:
      - 8080:8080
    volumes:
      - ./config/customer-management:/config
      - ../customer-core:/app/packages/customer-core

  customer-self-service:
    build:
      context: ..
      dockerfile: customer-self-service/Dockerfile
    depends_on:
      - customer-core
    ports:
      - 8080:8080
    volumes:
      - ./config/customer-management:/config
      - ../customer-core:/app/packages/customer-core

  test:
    build:
      context: ..
      dockerfile: ete-test/test/Dockerfile
    depends_on:
      - customer-management
    # command: tail -f /dev/null
